@startuml
participant "test: Test" as test
participant "type: TestType" as type
participant "testParam: TestParameter" as testParam
participant "testResult: TestParameterResult" as testResult
participant "em: ReferenceValueModule" as em

[o-> test : createTestParameterResult(paramCode, value, metric)
test -> test : getTestParameter(paramCode)
test -> testParam : param = getParameter()
test -> type : getExternalModule()
test -> em : getReferenceValue(param)
test -> testParam : createTestParameterResult(value, metric, refValue)
create testResult
testParam -> testResult : create(value, metric, refValue)
testResult -> testResult : validateValue(value)
testResult -> testResult : validateMetric(metric)
testResult -> testResult : validateRefValue(refValue)
@enduml