@startuml
autonumber

actor Administrator as admin
participant ":newLabUI" as UI
participant ":newLabController" as controller
participant ":Company" as validate
participant ":ClinicalAnalysisLaboratory" as lab

admin -> UI : registers a new clinical analysis laboratory
create controller
UI -> controller : create
UI -> controller : createLab()
controller -> validate : newLab = createLaboratory()
UI --> admin : request laboratory information (name, address, phonenumber, TIN, laboratory ID)
admin -> UI : gives requested data
UI -> controller : setData(name, address, phonenumber, TIN, laboratoryID)
controller -> lab : validate(name, address, phonenumber, TIN, laboratoryID)
UI --> admin : request types of tests
admin -> UI : selects requested data
UI -> controller : setTest()
UI --> admin : shows all the data and requests confirmation
admin -> UI : confirms the data
UI -> controller : saveLab()
UI --> admin : shows operation success
@enduml