@startuml
skinparam classAttributeIconSize 0

class Administrator
class Company
class ClinicalAnalysisLaboratory {
-name
-address
-phonenumber
-TIN
-laboratoryID
}
class TestType

Administrator "1 "---" *  " ClinicalAnalysisLaboratory : registers >
Company "1   " --- "*" ClinicalAnalysisLaboratory: owns >
Company "1" --- " * " TestType: conducts >
ClinicalAnalysisLaboratory "1  ‎ " - " *   ‎" TestType : performs >
@enduml