@startuml
class Administrator
class CreateNewLabUI{
+LabInfo(name, address, phonenumber, TIN, laboratoryID)
+TestType(testtype)
}
class CreateNewLabController {
+setData(name, address, phonenumber, TIN, laboratoryID)
+setTest(tt)
+saveData()
}
class Company {
-designation
+getTestType()
+getLab()
+createLab()
}
class ClinicalAnalysisLaboratory {
-String name
-String address
-int phonenumber
-int TIN
-String laboratoryID
-TestType tt
+validateName(name)
+validateAddress(address)
+validatePhoneNumber(phonenumber)
+validateTIN(TIN)
+validateLabID(laboratoryID)
}
class TestType

Administrator ..> newLabUI
newLabUI .> newLabController
newLabController ...> Company
newLabController .> ClinicalAnalysisLaboratory
Company"1"--"1..*"ClinicalAnalysisLaboratory : > owns
Administrator"1 "-"1..* "ClinicalAnalysisLaboratory : > registers
ClinicalAnalysisLaboratory"1   ‎ "--"1..*"TestType : > performs
Company" 1 "-" * "TestType : > conducts
Company"1   ‎"-"1..*"Administrator : > employs
Company .> newLabUI
@enduml