@startuml

skinparam classAttributeIconSize 0

class Test {
-testCode
-nhsCode
-designation
-dateTimeRegister
-dateTimeAnalysis
-dateTimeReport
-dateTimeValidation
}
class Client {
-name
-cardNumber
-birthDate
-sex
-nhsID
-TIF
-phoneNumber
-email
-password
}

Test "*"--"1" Client : requested by >

@enduml