@startuml

skinparam classAttributeIconSize 0

interface BiggestContiguousSumAlgorithm {
+int[] getBiggestContiguousSubSequence(int[] sequence)
}

class "BenchmarkAlgorithmAdapter" {
+int[] getBiggestContiguousSubSequence(int[] sequence)
}

class "BruteForceAlgorithmAdapter" {
+int[] getBiggestContiguousSubSequence(int[] sequence)
}

class "BenchmarkAlgorithm" {
+int[] Max(int[] seq)
}

class "BruteForceAlgorithm" {
+ArrayList<Integer> biggestSumSubSequence(int[] sequence)
}

"BenchmarkAlgorithmAdapter" ..up|> BiggestContiguousSumAlgorithm
"BruteForceAlgorithmAdapter" ..up|> BiggestContiguousSumAlgorithm
"BenchmarkAlgorithmAdapter" --down> "BenchmarkAlgorithm"
"BruteForceAlgorithmAdapter" --down> "BruteForceAlgorithm"
@enduml