@startuml
actor Administrator as admin
participant ":CreateEmployeeUI" as ui
participant ":CreateEmployeeController" as controller
participant ":???" as new
admin -> ui : **1** starts a new employee registration
create controller
ui -> controller : **2** create
ui -> controller : **3** createEmployee
controller -> new : **4** employee = createEmployee()
ui --> admin : **5** requests employee role
admin -> ui : **6** selects requested data
ui -> controller : **7** setRole(role)
controller -> new : **8** setRole(role)
ui --> admin : **7** requests employee information (ie. name, address, phone number, e-mail, **optional** DIN)
admin -> ui : **8** types requested data
ui -> controller : **9** setData(name, address, phone number, e-mail, **optional** DIN)
ui --> admin : **10** shows the data and requests confirmation
admin -> ui : **11** confirms the data
ui -> controller : **12** saveEmployee()
ui --> admin : **13** informs operation success


@enduml