@startuml

autonumber

actor Administrator as admin
participant ":createNewParameterUI" as UI
participant ":createNewParameterController" as Controller
participant ":Category" as cat
participant ":Parameter" as param
participant ":Company" as comp

admin -> UI: starts new parameter
UI -> Controller: getCategoryList()
Controller -> comp: getCategoryList()
comp -> Controller: categoryList
Controller -> UI: categoryList
UI --> admin: shows parameter category list and asks to pick the one that the new parameter falls under
admin -> UI: picks the wanted parameter category
UI --> admin: requests parameter information (ie. name, code, description)
admin -> UI: types in data
UI -> Controller: createNewParameter(shortName, code, description)
Controller -> cat: par = createNewParameter(shortName, code, description)
create param
cat -> param: create(shortName, code, description)
UI --> admin: shows all typed data and asks for confirmation
admin -> UI: confirms typed data
UI -> Controller: saveParameter(par)
Controller -> cat: saveParameter(par)
cat -> cat: validateParameter(par)
cat -> cat: addParameter(par)
UI --> admin: informs operation's success

@enduml