@startuml

autonumber

actor Administrator

Administrator -> ":System": starts new parameter
":System" -> Administrator: requests name of new parameter
Administrator -> ":System": types the name of the parameter that will be added
":System" -> Administrator: shows name that was typed in and asks for confirmation
Administrator -> ":System": confirms name of new parameter
":System" -> Administrator: requests code of the new parameter
Administrator -> ":System": types in code of new parameter
":System" -> Administrator: shows code typed in and asks for confirmation
Administrator -> ":System": confirms code
":System" -> Administrator: asks for a description of the new parameter
Administrator -> ":System": types in a description for the new parameter
":System" -> Administrator: shows that description and asks for confirmation
Administrator -> ":System": confirms description

@enduml