@startuml

class Administrator
class Parameter {
-int code
-String shortName
-String description
-double upperReferenceValue
-double lowerReferenceValue

+setShortName(shortName)
+setCode(code)
+setDescription(description)
+setUpperLower(upperReferenceValue, lowerReferenceValue)
}

class CreateNewParameterUI{
+parameterData(shortName, code, description, upperReferenceValue, lowerReferenceValue)
+parameterCategory(category)
}

class CreateNewParameterController{

+createNewParameter()
+setShortName(shortName)
+setCode(code)
+setDescription(description)
+setUpperLower(upperReferenceValue, lowerReferenceValue)
+saveParameter(category)
}

class Company

class Category {
-String code
-String description
-int nhsID
-ArrayList<Parameter>
}

class CatMapper{

+List<catDto> toDTO(List<Category> list)
+catDto toDTO(Category obj)
}

Administrator ...> CreateNewParameterUI
CreateNewParameterUI ...> CreateNewParameterController
CreateNewParameterController ...> Parameter
Category "*"--"1" Parameter : presented under <
Parameter "*"-up-"1" Administrator : specified by >
Company"1 "-"1..*" Administrator : > employs

@enduml