@startuml

skinparam classAttributeIconSize 0

class Administrator
class Parameter {
-int code
-String shortName
-String description
-double upperReferenceValue
-double lowerReferenceValue

+validateShortName(shortName)
+validateCode(code)
+validateDescription(description)
+validateUpperLower(upperReferenceValue, lowerReferenceValue)
}

class CreateNewParameterUI{
+parameterData(shortName, code, description, upperReferenceValue, lowerReferenceValue)
+parameterCategory(category)
}

class CreateNewParameterController{

+createNewParameter()
+setShortName(shortName)
+setCode(code)
+setDescription(description)
+setUpperLower(upperReferenceValue, lowerReferenceValue)
+saveParameter(category)
}

class Company

class Category {
-code
-description
-nhsID
-ArrayList<Parameter>
}

Administrator ..> CreateNewParameterUI
CreateNewParameterUI .> CreateNewParameterController
CreateNewParameterController ...> Company
Category "*"--"1" Parameter : presented under <
Parameter "*"-up-"1" Administrator : specified by >
Company"1   ‎"-"1..*"Administrator : > employs

@enduml