@startuml
skinparam classAttributeIconSize 0

class Client {
-name
-cardNumber
-birthDate
-sex
-nhsID
-TIF
-phoneNumber
-email
-password
}
class Receptionist
class Test {
-internalCode
-nhsCode
-createdAt
-designation
-dateAnalysis
-timeAnalysis
-dateDiagnosis
-timeDiagnosis
-dateValidation
-timeValidation
}