@startuml
actor Administrator as admin
participant ":CreateEmployeeUI" as ui
participant ":CreateEmployeeController" as controller
participant ":Company" as company
participant "roleStore: OrgRoleStore" as ors
participant ":OrganizationRole" as role
participant "e: Employee" as employee
participant "e: SpecialistDoctor" as sd
participant "empStore: EmployeeStore" as es
participant ":AuthFacade" as auth


admin -> ui : **1** starts a company employee registration
create controller
ui -> controller : **2** create()
ui -> controller : **3** getOrganizationRoles()
controller -> company : **4** roleStore = getOrgRolesStore()
controller -> ors : **5** roles = getOrganizationRoles()
ui --> admin : **6** requests employee role
admin -> ui : **7** selects requested data
ui --> admin : **8** requests employee information (ie. name, address, phone number, e-mail, soc, **optional** DIN)
admin -> ui : **9** types requested data
ui -> controller : **10** createEmployee(role, name, address, phoneNumber, email, soc, **optional** DIN)
controller -> es : **11** id = generateEmployeeId(name)
controller -> ors : **12** e = createEmployee(role, name, address, phoneNumber, email, soc, **optional** DIN)
alt role = "Specialist Doctor"
create sd
role -> sd : **13** create(id, role, name, address, phoneNumber, email, soc, DIN)
else
create employee
role -> employee : **14** create(id, role, name, address, phoneNumber, email, soc)
end
employee -> employee : **15** validateName(name)
employee -> employee : **16** validateAddress(address)
employee -> employee : **17** validatePhoneNumber(phoneNumber)
employee -> employee : **18** validateEmail(email)
employee -> employee : **19** validateSocCode(soc)
sd -> sd : **20** validate(DIN)
ui --> admin : **21** shows the data and requests confirmation
admin -> ui : **22** confirms the data
ui -> controller : **23** saveEmployee()
controller -> company : **24** empStore = getEmployeeStore()
controller -> es : **25** saveEmployee(e)
es -> es : **26** validateEmployee(e)
es -> es : **27** addEmployee(e)
controller -> company : **28** saveEmployeeAsUser(e)
company -> company : **29** pwd = generateUserPassword()
company -> auth : **30** addUserWithRole(e.getName(), e.getEmail(), pwd, e.getRoleId())
ui --> admin : **31** informs operation success


@enduml