@startuml

autonumber

actor "Laboratory Coordinator" as lc


lc -> System: clicks the import file menu
System -> lc: requests the file
lc -> System: selects the CSV file
System -> lc: informs operation (in)success

@enduml