@startuml
skinparam classAttributeIconSize 0
class Test {
-internalCode 
-nhsCode
-createdAt
-description 
-dateCollection 
-dateAnalysis 
-dateDiagnosis 
-dateValidation
}
class TestType {
-designation
-parameterList
}
class Client {
-name 
-cardNumber 
-birthDate 
-sex 
-nhsID
-TIF
-phoneNumber
-email
}
class Sample {
-barcode
}
class Parameter {
-designation
}
class "Lab Order" {
-testType 
-parameters 
}
class Company {
-designation
}
class Category {
-code
-description
-nhsID
}
class Administrator
class SampleType
class MedicalLabTechnician
class ClinicalChemistryTechnologist
class ChemicalLaboratory
class Receptionist
class TestResult
class SpecialistDoctor
class LabCoordinator
class Diagnosis
class NHS
class User {
-password
}
Client -left- "Lab Order" : has a >
Company -down- TestType : conducts >
Company -down- ChemicalLaboratory : owns >
Company -down- ClinicalAnalysisLaboratory : owns >
Test -down- "TestType" : is of >
Test -up- Client : requested by >
Test -down- Sample : collects >
Test -down- Parameter : requests analysis of >
Test -up- "Lab Order" : requires >
Test -up- Company : performs <
Test -down- TestResult : has a >
Test -up- NHS: requests report of <
Administrator -- Category : created by <
Parameter -- Category : presented under >
SampleType -up- Sample  : is of <
MedicalLabTechnician -up- Sample : collected by <
ClinicalChemistryTechnologist -up- Sample : analysed by <
ClinicalChemistryTechnologist -down- ChemicalLaboratory : works at >
Receptionist -left- Client : registers >
Receptionist -down- Test : registers >
TestResult -up- ClinicalChemistryTechnologist : generates <
TestResult -up- SpecialistDoctor : analysed by >
TestResult -up- LabCoordinator : validated by >
Diagnosis -up- SpecialistDoctor : generates <
Diagnosis -up- LabCoordinator : validated by >
Diagnosis -right- TestResult : associated to >

'Note:
'Consider the following generalizations: Employee and Laboratory
@enduml