@startuml
'https://plantuml.com/class-diagram

class ValidateTestUI

class ValidateTestController{
+getListTestsWithReport()

}

class TestStore{


}

class TestMapper{
+toDTO(listTestsWithReport)
}

class Company{
-TestStore testStore

+getListTestsWithReport()
}

ValidateTestUI ..> ValidateTestController
ValidateTestController ..> Company
ValidateTestController ..> TestMapper
Company --> TestStore

@enduml