@startuml

autonumber

actor LaboratoryCoordinator as LABCO
participant ":ValidateTestUI" as UI
participant ":ValidateTestController" as CTRL
participant ":TestStore" as STORE
participant ":TestMapper" as MAP
participant "listTestsWithReport : List <Test>" as testList
participant "listTestsWithReportDTO: List <TestDTO>" as testListDTO

activate LABCO
LABCO -> UI: Requests tests to validate
activate UI
UI -> CTRL: getListTestsWithReport()
activate CTRL
CTRL -> STORE: getListTestsWithReport()
activate STORE
deactivate STORE

CTRL -> MAP: listTestswithReportDto = toDTO(listTestsWithReport)
activate MAP
deactivate MAP

deactivate CTRL
UI --> LABCO: Shows list of tests ready to be validated
deactivate UI
LABCO -> UI: picks the tests to validate
loop until all the tests are validated
activate UI
UI --> LABCO: shows test's information (test registration date, chemical analysis date, diagnosis date)
LABCO -> UI: analyses the test dates and writes if it's valid or not
UI -> CTRL: validateTest()
activate CTRL
deactivate UI
CTRL -> STORE: validateTest(internalCode)
activate STORE
STORE -> STORE: validateTest(internalCode)
activate STORE
deactivate STORE
deactivate STORE
CTRL -> Company: sendNotification(internalCode))

end loop

deactivate LABCO


@enduml