@startuml
'https://plantuml.com/sequence-diagram

autonumber

":Laboratory coordinator" -> ":System": Requests the specialist doctor's/clinical chemistry technologist's work
":System" --> ":Laboratory coordinator": Shows the specialist doctor's/clinical chemistry technologist's work
":Laboratory coordinator" -> ":System": Reviews and validates the work done
":System" --> ":Laboratory coordinator": Confirms validation and (if results are valid) that the client has been sent notification that their results are available

@enduml