@startuml

autonumber

actor Administrator

Administrator -> ":System": starts parameter specification
loop until the administrator doesn't want to specify any more parameters
":System" -> Administrator: shows list of parameter categories and asks to choose the one the new parameter falls under
Administrator -> ":System": selects the parameter's category
":System" -> Administrator: requests parameter information (ie. name, code, description)
Administrator -> ":System": types in data
":System" -> Administrator: shows all typed data and asks for confirmation
Administrator -> ":System": confirms typed data
end loop
":System" -> Administrator: informs the operation's success

@enduml