@startuml
autonumber

participant "clientStore: ClientStore" as cstore
participant "client: Client" as client

[o-> cstore : updateClientData(client, dto)
cstore -> client : updateClientDate(dto)
client -> client : validateData()
client -> client : setData()

@enduml