@startuml
actor Administrator as admin
participant ":System" as sys

admin -> sys : **1** registers a new clinical analysis laboratory
sys --> admin : **2** request laboratory information (name, address, phonenumber, TIN, laboratory ID)
admin -> sys : **3** gives requested data
sys --> admin : **4** request types of tests
admin -> sys : **5** selects requested data
sys --> admin : **6** shows the given information and requests confirmation
admin -> sys : **7** confirms the data
sys --> admin : **8** shows operation success
@enduml