@startuml

autonumber

actor MedicalLabTechnician as mlt
participant ":System" as sys
mlt -> sys: records a new sample collected
sys -> mlt: requests number of samples to record
mlt -> sys: gives number of samples to record
sys -> mlt:

@enduml