@startuml

class SampleUI {
+TestCodeSelection(testList)
+setSampleNumber()
}

class SampleController {
+getTestList()
+setTestCode(testCode)
+setSampleNumber(n)
+createSampleList(n)
}

class ExternalModuleBarcodeAdapter {
}

interface ExternalModuleBarcode {
}

class Company {
}

class Sample {
-barcodeText
+generateBarcodeUCP()
}

class SampleList {
}

class TestStore {
}

class BarcodeAPI {
}

class Client {
}

class Test {
}

Sample "1"--"1 " BarcodeAPI : identified by >
Sample "*"--"1  " Client : associated to >
Test "1  "--"*" Sample : collects >

@enduml