@startuml

class MedicalLabTechnician
class Sample {
-barcode
}
class BarcodeAPI
class Client
class Test

Sample "1"--"1 " BarcodeAPI : identified by >
MedicalLabTechnician "1"--"*" Sample : collected by <
Sample "*"--"1  " Client : associated to >
Test "1  "--"*" Sample : collects >

@enduml