@startuml

autonumber

actor MedicalLabTechnician as mlt
participant SampleUI as UI
participant SampleController as Controller
participant Company
participant TestStore
participant Test
participant Sample
participant BarcodeAPI as API
participant SampleStore

activate mlt
mlt -> UI: requests to record new collected sample(s)
activate UI

UI --> mlt: requests test
deactivate UI

mlt -> UI: selects test
activate UI
UI -> Controller: getTestCode(int code)
activate Controller
Controller -> Company: getTest(int code)

UI --> mlt: requests number of samples to record
deactivate UI

mlt -> UI: gives number of samples to record
activate UI
loop loop for n times, n being the number of samples
UI -> Controller: createBarCode()
end loop

UI --> mlt: request confirmation
deactivate UI

mlt -> UI: gives confirmation
activate UI

UI --> mlt: gives (in)success of operation
deactivate UI
deactivate mlt

@enduml