@startuml
autonumber

actor Client as cli
participant ":ShowTestResultsUI" as ui
participant ":ShowTestResultsController" as controller
participant ":Company" as company
participant "clientStore: ClientStore" as cstore
participant "testStore:TestStore" as tstore
participant "test:Test" as test
participant "testMap: TestMapper" as tmap
participant "testParamList: TestParamList" as testparamls
participant "testParamMapper: TestParamMapper" as tpmap

activate cli
cli -> ui : accesses application to view results
activate ui
create controller
ui -> controller : create()
ui -> controller : displayClientTests(email)
activate controller
controller -> company : getClientStore()
activate company
|||
deactivate company
controller -> cstore : client = getClientByEmail(email)
activate cstore
|||
deactivate cstore
controller -> company : getTestStore()
activate company
|||
deactivate company
controller -> tstore : tests = getValidatedTestsByClient(client)
activate tstore
deactivate tstore
create tmap
controller -> tmap : create()
activate tmap
controller -> tmap : toDtoList(tests)
deactivate tmap
|||
deactivate tstore
deactivate controller
ui --> cli : displays client tests
deactivate ui
cli -> ui : selects a test
activate ui
ui -> controller : displayTestResults(testCode)
activate controller
controller -> tstore : test = getTestByCode(testCode)
activate tstore
|||
deactivate tstore
controller -> test : getTestParamList()
activate test
deactivate test
controller -> testparamls : testParams = getTestParameters()
activate testparamls
deactivate testparamls
create tpmap
controller -> tpmap : create(testParams)
activate tpmap
controller -> tpmap : toDtoList()
deactivate tpmap

deactivate controller

ui --> cli : displays test results
deactivate ui
@enduml