@startuml

participant TestListReadyForReportMapper as tlrm
participant "testListReadyForReport: List<Test>" as tlrfr
participant TestListReadyForReportDTO as tlrdto
participant "testDTO: TestDTO" as tdto



[o-> tlrm: toDTO(testListReadyForReport)
create tlrdto
tlrm -> tlrdto: create()
loop for every single object inside the testListReadyForReport
tlrm -> tlrfr: testReadyForReport = get(i)
activate tlrm
tlrm -> tlrm: testReadyForReportDTO = toDTO(testReadyForReport)
create tdto
tlrm -> tdto: create() não sei que parâmetros passar
deactivate tlrm
tlrm -> tlrdto: add(testReadyForReportDTO)
activate tlrdto
deactivate tlrdto
end loop
@enduml