@startuml

skinparam classAttributeIconSize 0

class Test {
-internalCode
-nhsCode
-createdAt
-designation
-dateAnalysis
-timeAnalysis
-dateDiagnosis
-timeDiagnosis
-dateValidation
-timeValidation
}

class SpecialistDoctor {
-doctorIndexNumber
}

class Diagnosis

class Report {
-textBody
}

Test "1"-down-"1" TestParameterResult: has a >
Test "1"-"1" Report: associated to >
Report "1"-"1" Diagnosis: contains >
TestParameterResult "1"-down-"1" SpecialistDoctor: analysed by >
SpecialistDoctor "1"-right-"*" Report: creates >

@enduml