@startuml
'https://plantuml.com/use-case-diagram

left to right direction
skinparam packageStyle rectangle
'Actors
:Receptionist:
:Medical Lab\n Technician: as MLT
:Clinical Chemistry\n Technologist: as CCT
:Specialist Doctor: as Doctor
:Laboratory Coordinator: as LC
:Client:
:Administrator:
:System\n Clock: as Clock

package Application {
    (Register test) as UC1
    (Register client) as UC2
    (Register sample) as UC3
    (Register analysis results) as UC4
    (Generate diagnosis) as UC5
    (Choose client sorting method) as UC6
    (Validate the clinical analysis) as UC7
    (View results) as UC8
    (Check results) as UC9
    (View statistics for number of tests waiting for result) as UC10
    (Access all client data) as UC11
    (Generate NHS report) as UC12
    (Specify new test) as UC13
    (Specify new test parameter) as UC14
    (Specify a new parameter category) as UC15
}

'Use Cases
Receptionist -- UC1
Receptionist -- UC2
UC3 -- MLT
CCT -- UC4
Doctor -- UC5
Administrator -- UC6
UC7 -- LC
UC8 -- Client
UC9 -- MLT
CCT -- UC9
UC9 -- LC
Doctor -- UC9
LC -- UC10
Doctor -- UC11
Clock -- UC12
Administrator -- UC13
Administrator -- UC14
Administrator -- UC15
@enduml