@startuml


autonumber

actor Administrator

Administrator -> ":CreateTestTypeUI": starts new test type
":CreateTestTypeUI" -> ":CreateTestTypeController": createTestType()
":CreateTestTypeController" -> ":Company": tt = createTestType()

":CreateTestTypeUI" -> Administrator: requests the designation
Administrator -> ":CreateTestTypeUI": types the designation
":CreateTestTypeUI" -> Administrator: requests the description of the collection method
Administrator -> ":CreateTestTypeUI": types the description

":CreateTestTypeUI" -> ":CreateTestTypeController": setTestType(designation, CollectionMethod)
":CreateTestTypeController" -> ":TestType": setDesignation(designation)
":CreateTestTypeController" -> ":CollectionMethod": setCollectionMethod(CollectionMethod)
":CreateTestTypeController" -> ":TestType": setCollectionMethodToTestType(CollectionMethod)

":CreateTestTypeUI" -> Administrator: shows and requests the categories
Administrator -> ":CreateTestTypeUI": types the wanted categories

":CreateTestTypeUI" -> ":CreateTestTypeController": addCategoriesToTestType(categories)
":CreateTestTypeController" -> ":TestType": setCategoriesToTestType(categories)
":CreateTestTypeController" -> ":Company": validateTestType(tt)
":CreateTestTypeUI" -> Administrator: shows the data (designation, CollectionMethod, Categories) and requests confirmation
Administrator -> ":CreateTestTypeUI": confirms the data
":CreateTestTypeUI" -> ":CreateTestTypeController": saveTestType()
":CreateTestTypeController" -> ":Company": saveTestType(tt)

":CreateTestTypeUI" -> Administrator: informs operation success



@enduml