@startuml

skinparam classAttributeIconSize 0

class Administrator
class CreateTestTypeUI {
+createTestType()
+setTestType(designation, CollectionMethod)
+addCategoriesToTestType(categories)
+saveTestType()
}
class CreateTestTypeController {
+displayCategoryList()
+createTestType()
+createCollectionMethod()
+setDesignation(String designation)
+setCollectionMethod(String description)
+setCollectionMethodToTestType(CollectionMethod cm)
+setCategoriesToTestType(Category category)
+saveTestType(tt)
}
class CollectionMethod {
-String description
+setCollectionMethod(CollectionMethod)
}
class TestType {
-String designation
-CollectionMethod collectionMethod
-Arraylist<Category> categories
+setDesignation(designation)
+setCategory(category)
+setCollectionMethod(collectionMethod)
+validateAttributes()
}
class Category {
-String code
-String description
-String nhsID
}
class Company {
-String designation
-ArrayList<TestType> testTypeList
+createTestType()
+createCollectionMethod()
+validate()
+validateTestType(tt)
+addTestType(tt)
+getCategoryList()
}

Administrator ..> CreateTestTypeUI
CreateTestTypeUI ..> CreateTestTypeController
TestType "*"-up-"1" Administrator : created by >
Category "1..*"-up-"1" TestType  : associated to <
TestType "1"--"1" CollectionMethod : has a  >
Company "1"-down-"*" TestType : conducts >
CreateTestTypeController ..> Company
CreateTestTypeController ..> TestType
CreateTestTypeController ..> CollectionMethod


@enduml