@startuml


autonumber

actor Administrator

Administrator -> ":CreateTestTypeUI": starts new test type
":CreateTestTypeUI" -> ":CreateTestTypeController": createTestType()
":CreateTestTypeUI" -> ":CreateTestTypeController": createCollectionMethod()
":CreateTestTypeController" -> ":Company": tt = createTestType()
":CreateTestTypeController" -> ":Company": cm = createCollectionMethod()
":Company" -> ":TestType": createTestType()
":Company" -> ":CollectionMethod": createCollectionMethod()

":CreateTestTypeUI" -> Administrator: requests the designation
Administrator -> ":CreateTestTypeUI": types the designation
":CreateTestTypeUI" -> Administrator: requests the description of the collection method
Administrator -> ":CreateTestTypeUI": types the description

":CreateTestTypeUI" -> ":CreateTestTypeController": setTestType(designation, CollectionMethod)
":CreateTestTypeController" -> ":TestType": setDesignation(designation)
":CreateTestTypeController" -> ":CollectionMethod": setCollectionMethod(description)
":CreateTestTypeController" -> ":TestType": setCollectionMethodToTestType(cm)

":Company" -> ":TestType": validate()
":TestType" -> ":TestType": validateAttributes()

":Company" -> ":CreateTestTypeController": getCategoryList()
":CreateTestTypeController" -> ":CreateTestTypeUI": displayCategoryList()

":CreateTestTypeUI" -> Administrator: shows and requests the categories
Administrator -> ":CreateTestTypeUI": types the wanted categories

":CreateTestTypeUI" -> ":CreateTestTypeController": addCategoriesToTestType(categories)
":CreateTestTypeController" -> ":TestType": setCategoriesToTestType(categories)
":CreateTestTypeUI" -> Administrator: shows the data (designation, CollectionMethod, Categories) and requests confirmation
Administrator -> ":CreateTestTypeUI": confirms the data
":CreateTestTypeUI" -> ":CreateTestTypeController": saveTestType()
":CreateTestTypeController" -> ":Company": saveTestType(tt)
":Company" -> ":Company": validateTestType(tt)
":Company" -> ":Company": addTestType(tt)

":CreateTestTypeUI" -> Administrator: informs operation success



@enduml