@startuml

autonumber

actor Administrator

Administrator -> ":System": starts new test type
":System" -> Administrator: requests the designation of the test
Administrator -> ":System": types the requested designation
":System" -> Administrator: shows the designation and requests a confirmation
Administrator -> ":System": confirms the name
":System" -> Administrator: requests a description of the collection methods
Administrator -> ":System": types the requested description
":System" -> Administrator: shows the description and requests a confirmation
Administrator -> ":System": confirms the description
":System" -> Administrator: shows a list of parameters
Administrator -> ":System": chooses parameters within the list to be associated to the new test type
":System" -> Administrator: shows the parameters chosen and requests confirmation
Administrator -> ":System": confirms the parameters

@enduml