@startuml

skinparam classAttributeIconSize 0

class Parameter {
-code
-shortName
-description
-upperReferenceValue
-lowerReferenceValue
}

class Category {
-name
-code
-description
-nhsID
}

Category "*"--"1" Parameter : presented under <

@enduml