@startuml
skinparam classAttributeIconSize 0

class Administrator

class Category {
-code
-description
-nhsID
}

class ClinicalChemistryTechnologist

class ChemicalLaboratory {
-name
-address
-phoneNumber
-TIN
}

class CollectionMethod {
-designation
}

class Client {
-name
-cardNumber
-birthDate
-sex
-nhsID
-TIF
-phoneNumber
-email
-password
}

class ClinicalAnalysisLaboratory {
-name
-address
-phoneNumber
-TIN
-laboratoryID
}

class Company {
-designation
}

class Employee {
-employeeID
-organizationID
-name
-address
-phoneNumber
-email
-SOCcode
}

class LaboratoryCoordinator
class MedicalLabTechnician
class NHS
class OrganizationRole
class Parameter {
-code
-shortName
-description
}

class Receptionist

class ReferenceValueModule

class Report {
-textReport
}

class Sample {
-barcode
}

class SpecialistDoctor {
-doctorIndexNumber
}

class Test {
-testCode
-nhsCode
-designation
-dateRegister
-timeRegister
-dateAnalysis
-timeAnalysis
-dateReport
-timeReport
-dateValidation
-timeValidation
}

class TestType {
-code
-description
}

class TestParameterResult {
-createdAt
-value
-metric
}

class Diagnosis



"NHS API" "1"-left-"*" NHSReportType : sent via <
(Test, Parameter) .. TestParameter
Administrator "1"--"*" Category : created by <
Administrator "1"--"*" Employee : registers >
ChemicalLaboratory "1"--"*" Sample : analyses >
ClinicalAnalysisLaboratory "1"--"*" Sample : collects >
ClinicalAnalysisLaboratory "1"--"*" TestType : performs >
ClinicalChemistryTechnologist "1"--"*" Sample : analysed by <
Company "1"--"1..*" Client : has >
Company "1"--"1..*" Employee : has >
Company "1"-down-"*" Category : has >
Company "1"-down-"*" ClinicalAnalysisLaboratory : owns >
Company "1"-down-"*" TestType : conducts >
Company "1"-down-"1" ChemicalLaboratory : owns >
Report "*"--"1" LaboratoryCoordinator : validated by >
Report "*"--"1" SpecialistDoctor : generates <
Employee -- OrganizationRole : has >
Employee <|-- SpecialistDoctor
MedicalLabTechnician "1"--"*" Sample : collected by <
"NHS API" -right- NHS : owned by >
NHSReportType "*"--"1" Company : generates <
OrganizationRole "0..*"--"1" Administrator : has <
OrganizationRole "0..*"--"1" ClinicalChemistryTechnologist : has <
OrganizationRole "0..*"--"1" LaboratoryCoordinator : has <
OrganizationRole "0..*"--"1" MedicalLabTechnician : has <
OrganizationRole "0..*"--"1" Receptionist : has <
Parameter "*"--"1" Category : presented under >
Receptionist "1"--"*" Client : registers >
Receptionist "1"--"*" Test : registers >
ReferenceValue "*"-up-"1" ReferenceValueModule : provided by >
Test -> Report: contains >
Sample "*"--"1" Client : associated to >
Sample "1"--"1" BarcodeAPI : identified by >
SpecialistDoctor "1"--"*" Report : generates >
Test "*"--"1" Client : requested by >
Test "*"--"1..*" Parameter : requests analysis of >
Test "*"-right-"1" "TestType" : is of >
Test "*"-up-"1" Company : performs <
Test "1"--"*" Sample : collects >
TestParameter "*"--"1" Parameter : associated to >
TestParameter "*"--"1" Test : has <
TestParameter "1"-right- "0..1" TestParameterResult : contains >
TestParameterResult "*"-right-"1" ClinicalChemistryTechnologist : generates <
TestParameterResult "1"--"1" Parameter : associated to >
TestParameterResult "1"-up-"1" ReferenceValue : records >
TestParameterResult "*"--"1" LaboratoryCoordinator : validated by >
TestParameterResult "*"--"1" SpecialistDoctor : analysed by >
TestType "*"--"1" Administrator : created by >
TestType "*"-right-"1" ReferenceValueModule : makes use of >
TestType "1"--"1" CollectionMethod : has a  >
TestType "1"--"1..*" Category : has >
Report "1"--"1" Diagnosis: contains >
@enduml