@startuml

skinparam classAttributeIconSize 0

class Test {
-internalCode
-nhsCode
-createdAt
-designation
-dateAnalysis
-timeAnalysis
-dateDiagnosis
-timeDiagnosis
-dateValidation
-timeValidation
}

class Diagnosis

class Report {
-textBody
}

class TestParameterResult {
-createdAt
-value
-metric
}


Test "1"-down-"1" TestParameter: has a >
TestParameter "1"-down-"1" TestParameterResult: contains >
Test "1"-"1" Report: associated to >
Report "1"-"1" Diagnosis: contains >
TestParameterResult -left- ReferenceValue: records >
ReferenceValue -down- ReferenceValueModule: provided by >

@enduml