@startuml

skinparam classAttributeIconSize 0

class Company {
-designation
}
class Test {
-testCode
-nhsCode
-designation
-dateRegister
-timeRegister
-dateAnalysis
-timeAnalysis
-dateReport
-timeReport
-dateValidation
-timeValidation
}
class Client {
-name
-cardNumber
-birthDate
-sex
-nhsID
-TIF
-phoneNumber
-email
-password
}
class MultiLinearRegression{
}
class LinearRegression{
}
class WriteReport{
}

"NHS API" "1"-left-"*" WriteReport : sent via <
"NHS API" -right- NHS : owned by >
MultiLinearRegression "*"--"1" Company : generates <
LinearRegression "*"--"1" Company : generates <
MultiLinearRegression "*"-up-"1" WriteReport : creates >
LinearRegression "*"-up-"1" WriteReport : creates >
Test "*"-up-"1" Company : performs <
Test "*"--"1" Client : requested by >

@enduml