@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as admin
participant ":System" as sys

admin -> sys: starts new report
sys -->admin :  asks initial and final date
admin -> sys : types requested data
sys --> admin : asks number and type of historical points
admin -> sys : types requested data
sys --> admin : requests regression model
admin -> sys : chooses regression
alt regression model is simple linear regression
sys --> admin : requests independent variable
admin -> sys : chooses independent variable
end
sys -> admin: informs operation success



@enduml