@startuml

autonumber

participant ":???" as a
participant "task : DailyReport" as task
participant "t : Timer" as timer

[o-> a : scheduleDailyReport(delay, interval)

activate a
create task
a --> task : create(argumentos necessarios para criar task)
create timer
a --> timer : create()
a -> timer : schedule(task, delay, interval)
activate timer
deactivate timer
deactivate a

note over a, timer : After the time specified by "delay" has elapsed

timer -> task : run()
activate timer
activate task
deactivate timer
deactivate task

note over a, timer : After the time specified by "interval" has elapsed

timer -> task : run()
activate timer
activate task
deactivate timer
deactivate task

@enduml

"task : OperationXTask" might be replaced by an instance of any subclass of TimerTask.
It receives the data/objects required for its correct operation through
its constructor or any other method this class has.