@startuml

skinparam classAttributeIconSize 0

class DailyReportController {
+dailyReportTimer()
+run()
}

class CreateNhsReportController {
+setHistoricalPoints(historicalPoints)
+setCurrentDay(currentDay)
+setInitialDay(initialDay)
+setFinalDay(finalDay)
+setIndependentVariable(independentVariable)
+makeRegression()
}

interface Runnable {
+run()
}

abstract TimerTask {
+run()
+cancel()
+scheduleExecutionTime()
}

class LinearRegression {
+LinearRegression(x, y)
}

class MultiLinearRegression {
+MultiLinearRegression(x1, x2, y)
}

class Company {
+makeMultiLinearRegressionReport(historicalPoints, dateCurrentDay, dateInitalDay, dateDayFinal)
+makeSimpleLinearRegressionReport(historicalPoints, dateCurrentDay, dateInitalDay, dateCurrentDayFinal, independentVar)
}

class WriteReport {
+WriteReport(testStore, historicalPoints, currentDay, startRegression, finishRegression)
+getReport()
}

interface ExternalModuleNhsReport {
+void sendReport(String string)
+void getDateAndTime()
}

class ExternalModuleNhsReportAdapter {
+sendReport(String string)
+getDateAndTime()
}

class Report2NHS {
+writeUsingFileWriter(String data)
}

DailyReportController ..> ExternalModuleNhsReport
Runnable <|.. TimerTask
TimerTask <|-- DailyReportController
DailyReportController .> CreateNhsReportController
CreateNhsReportController .> Company
Company ..> WriteReport
ExternalModuleNhsReport <|.. ExternalModuleNhsReportAdapter
ExternalModuleNhsReportAdapter --> Report2NHS
WriteReport ..> LinearRegression
WriteReport ..> MultiLinearRegression

@enduml