@startuml

skinparam classAttributeIconSize 0

class DailyReportController {
+run()
}

class CreateNhsReportController {
+setHistoricalPoints(historicalPoints)
+setCurrentDay(currentDay)
+setInitialDay(initialDay)
+setFinalDay(finalDay)
+setIndependentVariable(independentVariable)
+makeRegression()
}

interface Runnable {
+run()
}

abstract TimerTask {
+run()
+schedule(task, delay, period)
}

class DailyReportTimer {
+dailyReportTimer()
}

class LinearRegression {
+LinearRegression(x, y)
}

class MultiLinearRegression {
+MultiLinearRegression(x1, x2, y)
}

class Company {
+makeMultiLinearRegressionReport(historicalPoints, dateCurrentDay, dateInitalDay, dateDayFinal)
+makeSimpleLinearRegressionReport(historicalPoints, dateCurrentDay, dateInitalDay, dateCurrentDayFinal, independentVar)
}

class TestStore{
+getPositiveCasesPerDay(day)
+getNumberOfTestsPerformed(day)
+getAverageAgeClient(day)
}

class Category {
-code
-description
+getParameterOfTest()
}

class TestType {
-code
-description
+getCateforyOfTestType()
}

class Parameter {
-code
-description
+getParameterResultValue()
}

class WriteReport {
+WriteReport(testStore, historicalPoints, currentDay, startRegression, finishRegression)
+getReport()
}

interface ExternalModuleNhsReport {
+void sendReport(String string)
+void getDateAndTime()
}

class ExternalModuleNhsReportAdapter {
+sendReport(String string)
+getDateAndTime()
}

class Report2NHS {
+writeUsingFileWriter(String data)
}



DailyReportController ..> ExternalModuleNhsReport
TimerTask ..|> Runnable
DailyReportTimer ..> TimerTask
DailyReportTimer .> DailyReportController
DailyReportController .> CreateNhsReportController
CreateNhsReportController .> Company
Company "1    "-->"1  " TestStore : > has
Company "1"-->"*" WriteReport : > generates
TestStore <. WriteReport
ExternalModuleNhsReport <|.. ExternalModuleNhsReportAdapter
ExternalModuleNhsReportAdapter -> Report2NHS
WriteReport ..> LinearRegression
WriteReport ..> MultiLinearRegression
TestStore "1 "-->" * " TestType : > stores
Category " 1..* "->"  1 " TestType : > has
Parameter " * "-->" 1 " Category : presented under >
TestParameterResult " 1 "-->" 1 " Parameter : associated to >

@enduml