@startuml

skinparam classAttributeIconSize 0

class DailyReportController {
+dailyReportTimer()
+run()
}

class Company {
}

interface Runnable {
+run()
}

abstract TimerTask {
+run()
+cancel()
+scheduleExecutionTime()
}

class LinearRegression {
+LinearRegression(x, y)
}

class MultiLinearRegression {
+MultiLinearRegression(x1, x2, y)
}

class TestStore {
}

class WriteReport {
+WriteReport(testStore, historicalPoints, currentDay, startRegression, finishRegression)
+String getReport()
}

interface ExternalModuleNhsReport {
+void sendReport(String string)
}

class ExternalModuleNhsReportAdapter {
+sendReport(String string)
+getDateAndTime()
}

class Report2NHS {
+writeUsingFileWriter(String data)
}

DailyReportController ..> ExternalModuleNhsReport
Runnable <|.. TimerTask
TimerTask <|-- DailyReportController
DailyReportController ..> WriteReport
Company <. DailyReportController
TestStore <. Company
ExternalModuleNhsReport <|.. ExternalModuleNhsReportAdapter
ExternalModuleNhsReportAdapter ..> Report2NHS
LinearRegression <. WriteReport
WriteReport ..> MultiLinearRegression

@enduml